# Generated by go2rpm 1
%bcond_without check

# https://github.com/Azure/go-amqp
%global goipath         github.com/Azure/go-amqp
Version:                1.0.5

%gometa

%global common_description %{expand:
github.com/Azure/go-amqp is an AMQP 1.0 client implementation for Go.}

%global golicenses      LICENSE
%global godocs          CODE_OF_CONDUCT.md CONTRIBUTING.md README.md\\\
                        SECURITY.md

Name:           %{goname}
Release:        1%{?dist}
Summary:        AMQP 1.0 client library for Go

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

%if %{with check}
# Tests are disabled for now as github.com/stretchr/testify rebuild is a bit problematic
#BuildRequires:  golang(github.com/google/go-cmp/cmp)
#BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
#BuildRequires:  golang(github.com/fortytw2/leaktest)
#BuildRequires:  golang(github.com/stretchr/testify)
%endif

%description
%{common_description}

%gopkg

%prep
%goprep

%install
%gopkginstall

%if %{with check}
%check
#%gocheck
%endif

%gopkgfiles

%changelog
* Mon May 13 2024 Martin Magr <mmagr@redhat.com> - 1.0.5-1
- Fedora import

